### ISSUE TITLE
Assassin job gives you money for hits instead of kills

### ISSUE THREAD

**Issue by AGTHARN** [LousWiteMC/AdvancedJobs#1]
Title says it all. Please fix it, thank you!

**Comment by LousWiteMC** [comment]
okay i will fix it <3

Vào Th 2, 13 thg 4, 2020 vào lúc 09:17 AGTHARN <notifications@github.com>
đã viết:

**Comment by LousWiteMC** [comment]
i fixed it, please check it

Vào Th 2, 13 thg 4, 2020 vào lúc 14:47 LousWite MC <maxthedev76@gmail.com>
đã viết:

**Comment by AGTHARN** [comment]
Thanks. But I can't change the reward players get?

**Comment by LousWiteMC** [comment]
yes you can, you can change it on "Jobs.yml" file, edit the "Salary"

Vào Th 2, 13 thg 4, 2020 vào lúc 17:02 AGTHARN <notifications@github.com>
đã viết:

**Comment by LousWiteMC** [comment]
I updated, check it

Vào Th 2, 13 thg 4, 2020 vào lúc 17:40 LousWite MC <maxthedev76@gmail.com>
đã viết:

**Comment by LousWiteMC** [comment]
please check my update and submit please

Vào Th 2, 13 thg 4, 2020 vào lúc 17:48 LousWite MC <maxthedev76@gmail.com>
đã viết:

**Comment by AGTHARN** [comment]
Yeah it works, thanks
