### ISSUE TITLE
Glitch

### ISSUE THREAD

**Issue by MightyEclipseAWE** [LousWiteMC/AdvancedJobs#3]
This plugin can be a cheat of money, if you choose a job builder or wood cutter, it can be done in a protected lobby / spawn and done repeatedly

**Comment by hamid0740** [comment]
> This plugin can be a cheat of money, if you choose a job builder or wood cutter, it can be done in a protected lobby / spawn and done repeatedly

You can use https://github.com/hamid0740/JobUI instead

**Comment by LousWiteMC** [comment]
I have fixed it and this is the 0.3 version.
Link: https://drive.google.com/file/d/15hBNFSIqK3xuB5APY4pJYCs3CH-2bs5M/view?usp=sharing
